workflows:
  flutter-android:
    name: Flutter Android Build
    working_directory: mountaineering_app
    environment:
      flutter: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/mountaineering_app/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd mountaineering_app
          flutter pub get
      - name: Build Android App Bundle
        script: |
          cd mountaineering_app
          flutter build appbundle --release
      - name: Build APK
        script: |
          cd mountaineering_app
          flutter build apk --release
    artifacts:
      - mountaineering_app/build/app/outputs/bundle/release/app-release.aab
      - mountaineering_app/build/app/outputs/flutter-apk/app-release.apk
