default_platform(:ios)

platform :ios do
  desc "Sanal Mac üzerinden uygulamayı derle ve TestFlight'a yükle"
  lane :beta do
    
    # Apple API'ye Bağlan
    app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_ISSUER_ID"],
      key_content: ENV["API_KEY_CONTENT"],
      is_key_content_base64: false,
      in_house: false
    )

    # Sertifika ve Provisioning profillerini otomatik oluştur
    cert(
      keychain_password: ""
    )
    sigh(force: true)

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "App.xcodeproj",
      team_id: "TAH5CSWX56",
      bundle_identifier: "com.rotaplus.emniyetteyim",
      profile_name: ENV["SIGH_NAME"],
      code_sign_identity: "Apple Distribution"
    )

    # Xcode Derlemesini Başlat
    build_app(
      project: "App.xcodeproj",
      scheme: "App",
      export_method: "app-store"
    )

    # Derlenen uygulamayı App Store Connect'e gönder
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
