name: iOS Build and TestFlight Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Kodları Al
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Disable Swift Package Manager
        run: flutter config --no-enable-swift-package-manager

      - name: Flutter Dependencies
        working-directory: ./mountaineering_app
        run: flutter pub get

      - name: Eksik iOS Dosyalarını Oluştur
        working-directory: ./mountaineering_app
        run: flutter create . --platforms ios

      - name: Podfile Platformunu Düzelt ve Pod Install
        working-directory: ./mountaineering_app/ios
        run: |
          # Podfile içindeki tüm platform tanımlarını temizleyip en üste iOS 15.0 ekliyoruz
          ruby -i -e "lines = ARGF.readlines; lines.reject! { |l| l.match?(/platform :ios/) }; puts \"platform :ios, '15.0'\"; puts lines" Podfile
          # Xcode projesi içindeki minimum versiyonu iOS 15.0 yapıyoruz
          ruby -i -e "puts ARGF.read.gsub(/IPHONEOS_DEPLOYMENT_TARGET = .*?;/, %{IPHONEOS_DEPLOYMENT_TARGET = 15.0;})" Runner.xcodeproj/project.pbxproj
          pod repo update
          pod install

      - name: Bundle Identifier Ayarla
        working-directory: ./mountaineering_app/ios
        run: |
          sed -i '' 's/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = com.rotaplus.emniyetteyim;/g' Runner.xcodeproj/project.pbxproj

      - name: Flutter Build iOS
        working-directory: ./mountaineering_app
        run: flutter build ios --release --no-codesign

      - name: Ruby ve Fastlane Kur
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Fastlane Yükle
        working-directory: ./mountaineering_app/ios
        run: bundle install

      - name: App Store'a Derle ve Yükle
        working-directory: ./mountaineering_app/ios
        env:
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          API_ISSUER_ID: ${{ secrets.API_ISSUER_ID }}
          API_KEY_CONTENT: ${{ secrets.API_KEY_CONTENT }}
        run: bundle exec fastlane beta
